export const ADD_TODO = 'TODO/ADD_TODO';
export const EDIT_TODO = 'TODO/EDIT_TODO';
export const REMOVE_TODO = 'TODO/REMOVE_TODO';
export const TOGGLE_COMPLETED_TODO = 'TODO/TOGGLE_COMPLETED_TODO';
export const REMOVE_COMPLETED_TODOS = 'TODO/REMOVE_COMPLETED_TODOS';

export const SET_FILTER = 'APP/SET_FILTER';
